import type { StoreState } from "./index";

type StateSelector = (state: StoreState) => any;

export type TemplateMapping = {
  [apiKey: string]: keyof StoreState | StateSelector;
};

const gucciMapping: TemplateMapping = {
  storeLocation: "gucciStoreLocation",
  storeAddress1: "gucciStoreAddress1",
  storeAddress2: "gucciStoreAddress2",
  storeCityZip: "gucciStoreCityZip",
  storePhoneFax: "gucciStorePhoneFax",
  date: "gucciDate",
  transNumber: "gucciTransNumber",
  storeId: "gucciStoreId",
  registerId: "gucciRegisterId",
  cashierName: "cashierName",
  customerName: "customerName",
  customerId: "gucciCustomerId",
  productSku: "gucciProductSku",
  itemPrice: "gucciProductPrice",
  productName: "gucciProductName",
  productAmount: "gucciProductPrice",
  salesperson: "gucciSalesperson",
  subtotal: "gucciSubtotal",
  tax: "gucciProductTax",
  total: "gucciTotal",
  paymentMethod: "gucciPaymentMethod",
  paymentAmount: "gucciPaymentAmount",
  change: "gucciChange",
  itemCount: "gucciItemCount",
  taxAnalysisCode: "gucciTaxAnalysisCode",
  taxAnalysisTaxable: "gucciTaxAnalysisTaxable",
  taxAnalysisRate: "gucciTaxAnalysisRate",
  taxAnalysisTotal: "gucciTaxAnalysisTotal",
  taxAnalysisTax: "gucciTaxAnalysisTax",
};

const sephoraMapping: TemplateMapping = {
  storeName: "sephoraStoreName",
  storeAddress: "sephoraStoreAddress1",
  storeCityStateZip: "sephoraStoreAddress2",
  productName: "sephoraProductName",
  productSku: "sephoraProductSku",
  productQty: "sephoraProductQty",
  itemPrice: "sephoraPrice",
  productAmount: "sephoraProductAmount",
  subtotal: "sephoraSubtotal",
  taxDesc: "sephoraTaxDesc",
  taxPercent: "sephoraTaxPercent",
  taxAmount: "sephoraTax",
  totalAmount: "sephoraTotalAmount",
  paymentType: "sephoraPaymentType",
  paymentAmount: "sephoraPaymentAmount",
  cardNumberMasked: "sephoraCardNumberMasked",
  cardType: "sephoraCardType",
  cardEntry: "sephoraCardEntry",
  transType: "sephoraTransType",
  authCode: "sephoraAuthCode",
  sequenceNum: "sephoraSequenceNum",
  referenceNum: "sephoraReferenceNum",
  terminalId: "sephoraTerminalId",
  date: "sephoraDate",
  time: "sephoraTime",
  approvalStatus: "sephoraApprovalStatus",
  cashierName: "cashierName",
  customerName: "customerName",
};

const diorMapping: TemplateMapping = {
  store_phone: "diorStorePhone",
  store_address: "diorStoreAddress",
  store_city_state_zip: "diorStoreCityStateZip",
  store_id: "diorStoreId",
  date: "diorDate",
  time: "diorTime",
  register_id: "diorRegisterId",
  trans_counter: "diorTransCounter",
  cashier_id: "diorCashierId",
  customer_name: "customerName",
  customer_id: "diorCustomerId",
  store_name: "diorStoreName",
  product_name: "diorProductName",
  product_sku: "diorProductSku",
  salesperson_id: "diorSalespersonId",
  total_amount: "diorTotalAmount",
  tax_rate: "diorTaxRate",
  tax_amount: "diorTaxAmount",
  subtotal: "diorSubtotal",
  item_price: "diorItemPrice",
  card_last_4: "diorCardLast4",
  tax_rate_detail: "diorTaxRateDetail",
  tax_amount_detail: "diorTaxAmountDetail",
  taxable_amount_detail: "diorTaxableAmountDetail",
  tax_total_detail: "diorTaxTotalDetail",
  transaction_id: "diorTransactionId",
  cashierName: "cashierName",
};

const appleMapping: TemplateMapping = {
  appleStoreLocation: "appleStoreLocation",
  appleDateTime: "appleDateTime",
  appleProductName: "appleProductName",
  applePartNumber: "applePartNumber",
  appleReturnDate: "appleReturnDate",
  appleSubTotal: "appleSubTotal",
  appleTaxRate: "appleTaxRate",
  appleTaxAmount: "appleTaxAmount",
  appleTotal: "appleTotal",
  applePaymentMethod: "applePaymentMethod",
  appleCardNumber: "appleCardNumber",
  appleTransactionDateTime: "appleTransactionDateTime",
  appleApplicationId: "appleApplicationId",
  appleApplicationPanSequence: "appleApplicationPanSequence",
  appleDeviceId: "appleDeviceId",
  appleCardType: "appleCardType",
  applePreferredName: "applePreferredName",
  appleTvr: "appleTvr",
  appleTsi: "appleTsi",
  appleTransactionCode: "appleTransactionCode",
  customerName: "customerName",
  cashierName: "cashierName",
};

const dysonMapping: TemplateMapping = {
  storeName: "dysonStoreName",
  storeAddress: "dysonStoreAddress",
  storeCity: "dysonStoreCity",
  storePhone: "dysonStorePhone",
  date: "dysonDate",
  orderNumber: "dysonOrderNumber",
  orderReference: "dysonOrderReference",
  customerName: "dysonCustomerName",
  customerEmail: "dysonCustomerEmail",
  productName: "dysonProductName",
  productModel: "dysonProductModel",
  productSku: "dysonProductSKU",
  serialNumber: "dysonSerialNumber",
  price: "dysonPrice",
  tax: "dysonTax",
  cardLast4: "dysonCardLast4",
};

const flightClubMapping: TemplateMapping = {
  productName: "flightClubProductName",
  orderNumber: "flightClubOrderNumber",
  date: "flightClubDate",
  storeAddress: "flightClubStoreAddress",
  storeCityStateZip: "flightClubStoreCityStateZip",
  storePhone: "flightClubStorePhone",
  productSku: "flightClubProductSKU",
  productSize: "flightClubProductSize",
  itemPrice: "flightClubItemPrice",
  subtotal: "flightClubSubtotal",
  taxAmount: "flightClubTaxAmount",
  totalAmount: "flightClubTotalAmount",
  discountAmount: "flightClubDiscountAmount",
  tenderedCash: "flightClubTenderedCash",
  tenderedCreditCard: "flightClubTenderedCreditCard",
  changeAmount: "flightClubChangeAmount",
  customerName: "customerName",
  cashierName: "cashierName",
};

const flannelsMapping: TemplateMapping = {
  flannelsStoreAddress: "flannelsStoreAddress",
  flannelsStoreCityStateZip: "flannelsStoreCityStateZip",
  flannelsEmployeeId: "flannelsEmployeeId",
  flannelsEmployeeNumber: "flannelsEmployeeNumber",
  flannelsProductSku: "flannelsProductSku",
  flannelsProductName: "flannelsProductName",
  flannelsItemPrice: "flannelsItemPrice",
  flannelsSubtotal: "flannelsSubtotal",
  flannelsTaxAmount: "flannelsTaxAmount",
  flannelsTotal: "flannelsTotal",
  flannelsPaymentMethod: "flannelsPaymentMethod",
  flannelsPaymentAmount: "flannelsPaymentAmount",
  flannelsCardNumberMasked: "flannelsCardNumberMasked",
  flannelsMerchantNumber: "flannelsMerchantNumber",
  flannelsTerminalNumber: "flannelsTerminalNumber",
  flannelsAppId: "flannelsAppId",
  flannelsAuthCode: "flannelsAuthCode",
  flannelsStoreId: "flannelsStoreId",
  flannelsTillId: "flannelsTillId",
  flannelsTransactionNumber: "flannelsTransactionNumber",
  flannelsDate: "flannelsDate",
  flannelsTime: "flannelsTime",
  flannelsOperatorId: "flannelsOperatorId",
  flannelsItemCount: "flannelsItemCount",
  flannelsVatNumber: "flannelsVatNumber",
  flannelsBarcodeNumber: "flannelsBarcodeNumber",
  customerName: "customerName",
  cashierName: "cashierName",
};

const stussyMapping: TemplateMapping = {
  STORE_ADDRESS_LINE1: "stussyStoreAddressLine1",
  STORE_CITY: "stussyStoreCity",
  STORE_PHONE: "stussyStorePhone",
  DATE_TIME: "stussyDateTime",
  TICKET_NUMBER: "stussyTicketNumber",
  VAT_NUMBER: "stussyVatNumber",
  REGISTER: "stussyRegister",
  EMPLOYEE: "stussyEmployee",
  PRODUCT_NAME: "stussyProductName",
  PRODUCT_PRICE: "stussyProductPrice",
  PRODUCT_SIZE: "stussyProductSize",
  SUBTOTAL: "stussySubtotal",
  TAX_BASE: "stussyTaxBase",
  TAX_RATE: "stussyTaxRate",
  TAX_AMOUNT: "stussyTaxAmount",
  TOTAL: "stussyTotal",
  PAYMENT_METHOD: "stussyPaymentMethod",
  BARCODE_NUMBER: "stussyBarcodeNumber",
  customerName: "customerName",
  cashierName: "cashierName",
};

const lvMapping: TemplateMapping = {
  STORE_NAME: "lvStoreName",
  STORE_ADDRESS_LINE: "lvStoreAddressLine",
  STORE_CITY_POSTAL: "lvStoreCityPostal",
  STORE_COUNTRY: "lvStoreCountry",
  STORE_PHONE: "lvStorePhone",
  STORE_SIRET: "lvStoreSiret",
  STORE_NAF: "lvStoreNaf",
  STORE_TVA_NUMBER: "lvStoreTvaNumber",
  STORE_SIREN: "lvStoreSiren",
  SIGNATURE_CODE: "lvSignatureCode",
  DOCUMENT_NUMBER: "lvDocumentNumber",
  POS_SOFTWARE_VERSION: "lvPosSoftwareVersion",
  STORE_ID: "lvStoreId",
  REGISTER_ID: "lvRegisterId",
  DATE: "lvDate",
  TIME: "lvTime",
  TRANSACTION_ID: "lvTransactionId",
  SALES_ASSOCIATE: "lvSalesAssociate",
  CUSTOMER_NAME: "lvCustomerName",
  PRODUCT_DESCRIPTION: "lvProductDescription",
  PRODUCT_CODE: "lvProductCode",
  QUANTITY: "lvQuantity",
  VAT_RATE: "lvVatRate",
  UNIT_PRICE_HT: "lvUnitPriceHt",
  UNIT_PRICE_TTC: "lvUnitPriceTtc",
  TOTAL_TTC: "lvTotalTtc",
  TOTAL_HT: "lvTotalHt",
  TOTAL_TAX: "lvTotalTax",
  PAYMENT_METHOD: "lvPaymentMethod",
  AMOUNT_PAID: "lvAmountPaid",
  CHANGE_GIVEN: "lvChangeGiven",
};

const balenciagaMapping: TemplateMapping = {
  storeName: "balenciagaStoreName",
  storeAddress: "balenciagaStoreAddress",
  storeCity: "balenciagaStoreCity",
  storeZip: "balenciagaStoreZip",
  storePhone: "balenciagaStorePhone",
  transactionNumber: "balenciagaTransactionNumber",
  date: "balenciagaDate",
  time: "balenciagaTime",
  cashier: "balenciagaCashier",
  register: "balenciagaRegister",
  customerId: "balenciagaCustomerId",
  currency: "balenciagaCurrency",
  products: "balenciagaProducts",
  subtotal: "balenciagaSubtotal",
  tax: "balenciagaTax",
  total: "balenciagaTotal",
  paymentMethod: "balenciagaPaymentMethod",
  paymentAmount: "balenciagaPaymentAmount",
  change: "balenciagaChange",
  itemCount: "balenciagaItemCount",
  taxAnalysis: "balenciagaTaxAnalysis",
  customerName: "balenciagaCustomerName",
};

const samsungMapping: TemplateMapping = {
  storeName: "samsungStoreName",
  storeAddress: "samsungStoreAddress",
  storeCity: "samsungStoreCity",
  storePhone: "samsungStorePhone",
  date: "samsungDate",
  customerName: "samsungCustomerName",
  customerId: "samsungCustomerId",
  customerEmail: "samsungCustomerEmail",
  products: "samsungProducts",
  subtotal: "samsungSubtotal",
  taxItems: "samsungTaxItems",
  total: "samsungTotal",
  paymentMethod: "samsungPaymentMethod",
  cardLast4: "samsungCardLast4",
  orderNumber: "samsungOrderNumber",
  serialNumber: "samsungSerialNumber",
};

const adidasMapping: TemplateMapping = {
  storeId: "adidasStoreId",
  storeName: "adidasStoreName",
  storeAddress: "adidasStoreAddress",
  storeCity: "adidasStoreCity",
  storePhone: "adidasStorePhone",
  transactionId: "adidasTransactionId",
  dateTime: "adidasDateTime",
  products: "adidasProducts",
  subtotal: "adidasSubtotal",
  taxLabel: "adidasTaxLabel",
  tax: "adidasTax",
  total: "adidasTotal",
  payment: "adidasPayment",
  balance: "adidasBalance",
  paymentMethod: "adidasPaymentMethod",
  paymentDate: "adidasPaymentDate",
  paymentAmount: "adidasPaymentAmount",
  referenceNumber: "adidasReferenceNumber",
  authNumber: "adidasAuthNumber",
  cardLast4: "adidasCardLast4",
};

const footLockerMapping: TemplateMapping = {
  productName: "footLockerProductName",
  price: "footLockerPrice",
  tax: "footLockerTax",
  total: "footLockerTotal",
  dateTime: "footLockerDateTime",
  date: "footLockerDate",
  orderNumber: "footLockerOrderNumber",
  storeNumber: "footLockerStoreNumber",
  register: "footLockerRegister",
  cashier: "footLockerCashier",
  productSKU: "footLockerProductSKU",
  cardLast4: "footLockerCardLast4",
  approvalCode: "footLockerApprovalCode",
  storeName: "footLockerStoreName",
  storeAddress: "footLockerStoreAddress",
  storeAddressLine2: "footLockerStoreAddressLine2",
  storeCity: "footLockerStoreCity",
  storeZip: "footLockerStoreZip",
  storePhone: "footLockerStorePhone",
  associateNumber: "footLockerAssociateNumber",
  cardExpiry: "footLockerCardExpiry",
  taxRate: "footLockerTaxRate",
  taxableAmount: "footLockerTaxableAmount",
  quantity: "footLockerQuantity",
  validationCode: "footLockerValidationCode",
};

const threeUkMapping: TemplateMapping = {
  brandName: "threeUkBrandName",
  branchName: "threeUkBranchName",
  storeAddress: "threeUkStoreAddress",
  storeCity: "threeUkStoreCity",
  storePhone: "threeUkStorePhone",
  productName: "threeUkProductName",
  productPrice: "threeUkProductPrice",
  productImei: "threeUkProductImei",
  invoiceNumber: "threeUkInvoiceNumber",
  servedBy: "threeUkServedBy",
  vatNumber: "threeUkVatNumber",
  transactionDate: "threeUkTransactionDate",
  transactionTime: "threeUkTransactionTime",
  transactionStore: "threeUkTransactionStore",
  transactionTerm: "threeUkTransactionTerm",
  transactionCode: "threeUkTransactionCode",
};

const goyardMapping: TemplateMapping = {
  storeName: "goyardStoreName",
  storeAddress: "goyardStoreAddress",
  storeCity: "goyardStoreCity",
  storePhone: "goyardStorePhone",
  orderNumber: "goyardOrderNumber",
  date: "goyardDate",
  time: "goyardTime",
  storeId: "goyardStoreId",
  cashierId: "goyardCashierId",
  transactionNumber: "goyardTransactionNumber",
  customerId: "goyardCustomerId",
  customerName: "goyardCustomerName",
  quantity: "goyardProductQuantity",
  productName: "goyardProductName",
  productPrice: "goyardProductPrice",
  productReference: "goyardProductReference",
  productColor: "goyardProductColor",
  cardMask: "goyardCardLast4",
  paymentMethod: "goyardPaymentMethod",
  paymentAmount: "goyardPaymentAmount",
  currency: "goyardCurrency",
  taxLabel: "goyardTaxLabel",
  taxAmount: "goyardTaxAmount",
  taxRate: "goyardTaxRate",
  taxBaseAmount: "goyardTaxBaseAmount",
  vatNumber: "goyardVatNumber",
  salesAssociate: "goyardSalesAssociate",
};

const gucciNycMapping: TemplateMapping = {
  transNumber: "gucciTransNumber",
  transDateTime: "gucciTransDateTime",
  storeNumber: "gucciStoreNumber",
  registerNumber: "gucciRegisterNumber",
  cashierId: "gucciCashierId",
  customerName: "gucciCustomerName",
  customerId: "gucciCustomerId",
  itemSku: "gucciItemSku",
  itemQty: "gucciItemQty",
  itemPrice: "gucciItemPrice",
  itemTotalAmount: "gucciItemTotalAmount",
  itemDescription: "gucciItemDescription",
  itemSize: "gucciItemSize",
  itemStyleNumber: "gucciItemStyleNumber",
  itemExtraDetails: "gucciItemExtraDetails",
  salespersonId: "gucciSalespersonId",
  salespersonName: "gucciSalespersonName",
  subtotal: "gucciSubtotal",
  taxAmount: "gucciTaxAmount",
  totalAmount: "gucciTotalAmount",
  distanceSalesAmount: "gucciDistanceSalesAmount",
  distanceSalesId: "gucciDistanceSalesId",
  changeAmount: "gucciChangeAmount",
  soldItemCount: "gucciSoldItemCount",
  taxCode: "gucciTaxCode",
  taxableAmount: "gucciTaxableAmount",
  taxRate: "gucciTaxRate",
  taxTotal: "gucciTaxTotal",
  taxAmountFinal: "gucciTaxAmountFinal",
};

export const templateMappings: Record<string, TemplateMapping> = {
  gucci: gucciMapping,
  gucci_nyc: gucciNycMapping,
  sephora: sephoraMapping,
  dior: diorMapping,
  apple: appleMapping,
  dyson: dysonMapping,
  flight_club: flightClubMapping,
  flannels: flannelsMapping,
  stussy: stussyMapping,
  lv: lvMapping,
  balenciaga: balenciagaMapping,
  samsung: samsungMapping,
  adidas: adidasMapping,
  foot_locker: footLockerMapping,
  three_uk: threeUkMapping,
  goyard: goyardMapping,
};
